version: '3.3'

services:

  customerOne:
    image: spring-boot-3-and-distributed-tracing-one:0.0.1-SNAPSHOT
    hostname: customerOne
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'
    environment:
      - CUSTOMER_DETAILS_HOST=http://customer-detail:8080
    networks:
      - app-network

  customerTwo:
    image: spring-boot-3-and-distributed-tracing-one:0.0.1-SNAPSHOT
    hostname: customerTwo
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'
    environment:
      - CUSTOMER_DETAILS_HOST=http://customer-detail:8080
    networks:
      - app-network      

  customerDetail:
    image: spring-boot-3-and-distributed-tracing-two:0.0.1-SNAPSHOT
    hostname: customer-detail
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - customerOne
      - customerTwo
      - customerDetail
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '256MB'

networks:
  app-network:
