spring:
    application:
        name: spring-boot-3-and-distributed-tracing-one

server.port: 8079

logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
    level:
        org.apache.http: DEBUG
        httpclient.wire: DEBUG
        org:
            springframework:
                web:
                    client:
                        RestTemplate: DEBUG
management:
    endpoints:
        web:
            exposure:
                include: '*'

    tracing:
        sampling:
            probability: 1.0
        propagation:
            type: w3c
        enabled: true
        baggage:
            enabled: true
    metrics:
        distribution:
            percentiles-histogram:
                http:
                    server:
                        requests: true
