spring:
  application.name: addresses
  datasource:
    url: jdbc:h2:mem:addressdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    h2.console.enabled: true

server.port: 8085

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

  level:
    org.apache.http: DEBUG
    httpclient.wire: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
  log4j.rootLogger: DEBUG, stdout